services:
  web:
    build: ./web
    ports:
      - "8080:5000"
    environment:
      REDIS_HOST: redis
      APP_TITLE: Docker Compose od podstaw
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
